name:                my-fsm-stack-package
version:             0.0.1.0
github:              "Pablo-Dominguez/my-stack-fsm-package"
license:             BSD3
author:              "Pablo Dominguez"
maintainer:          "pabdombal@alum.us.es"
copyright:           "2020 Pablo Dominguez"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Pablo-Dominguez/my-stack-fsm-package#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- matrix
- vector

library:
  source-dirs: src

executables:
  my-fsm-stack-package-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - my-fsm-stack-package

tests:
  my-fsm-stack-package-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - my-fsm-stack-package
